[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "url_shortener_backend"
version = "0.1.0"
dependencies = [
    "pytest",
    "fastapi",
]
